version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: quant_engine
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d quant_engine" ]
      interval: 5s
      timeout: 5s
      retries: 5

  algo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: algo-app
    volumes:
      - .:/app
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_HOST=timescaledb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=quant_engine

volumes:
  timescaledb_data:
