from loguru import logger
from .broker import MockBrokerAPI

class OrderManagementSystem:
    """OMS handles signals generated by the model and sends them to the broker."""
    
    def __init__(self, broker: MockBrokerAPI):
        self.broker = broker

    def execute_signal(self, symbol: str, signal: int, price: float, quantity: int = 1):
        """
        Translates a model signal into a broker order.
        Signal convention: 0 = HOLD, 1 = BUY, 2 = SELL
        """
        if signal == 0:
            logger.debug(f"Hold signal for {symbol}. No action taken.")
            return

        side = "BUY" if signal == 1 else "SELL"
        logger.info(f"Signal received: {side} {quantity} {symbol} @ {price}")
        
        success = self.broker.place_order(symbol, quantity, side, price)
        if success:
            logger.info(f"Successfully executed {side} order for {symbol}.")
        else:
            logger.error(f"Failed to execute {side} order for {symbol}.")
